export {default as Hero} from './Hero'
export {default as OffersSection} from './OffersSection'
export {default as About} from './About'
export {default as Services} from './Services'
export {default as Form} from './Form'